#!/bin/bash
#  Elemental — CLI build. No Xcode project, no Metal toolchain.
#
#  Scene.metal is embedded into the binary as a Swift string and compiled by the
#  Metal runtime at launch. That is what makes the screensaver work: it does no
#  file I/O at all, so the legacyScreenSaver sandbox has nothing to deny.
#
#  Usage:  ./build.sh [render|app|saver|all]      (default: all)

set -euo pipefail
cd "$(dirname "$0")"

export DEVELOPER_DIR=/Library/Developer/CommandLineTools
TARGET="${1:-all}"
BUILD="build"
mkdir -p "$BUILD"

# ---------------------------------------------------------------- shader embed
# Regenerate Core/ShaderSource.swift from Core/Scene.metal. Edit the .metal
# file; never edit the generated .swift.
embed_shader() {
  local src="Core/Scene.metal" out="Core/ShaderSource.swift"
  if [[ -f "$out" && "$out" -nt "$src" ]]; then return; fi
  echo "  embedding $src"
  {
    echo "//  ShaderSource.swift — GENERATED by build.sh from Core/Scene.metal."
    echo "//  Do not edit. Edit Scene.metal and rebuild."
    echo ""
    echo "enum ShaderSource {"
    echo "    static let metal = #\"\"\""
    cat "$src"
    echo "\"\"\"#"
    echo "}"
  } > "$out"
}

# Config lives in Core because the saver needs it too — it tries to read the
# app's settings and falls back to defaults when the sandbox says no.
CORE=(Core/SceneState.swift Core/Astro.swift Core/Simulation.swift \
      Core/Renderer.swift Core/Config.swift Core/Weather.swift \
      Core/Furniture.swift Core/Observation.swift Core/Calibration.swift \
      Core/SkyImagery.swift Core/Updater.swift Core/ShaderSource.swift)

SWIFTFLAGS=(-O -wmo)

# ---------------------------------------------------------------- targets


# ------------------------------------------------------------------ signing
#
# Two modes, chosen by whether a Developer ID identity is configured.
#
#   ad hoc (default)   `codesign -s -`. Fine on the machine that built it and
#                      nowhere else: Gatekeeper refuses an ad-hoc bundle on any
#                      other Mac with "Elemental is damaged and can't be
#                      opened", which is a lie but an unhelpful one. It also
#                      mints a new code hash every build, so macOS forgets TCC
#                      grants — trap 9 in HANDOFF.md, and why Location keeps
#                      needing re-approval during development.
#
#   Developer ID       for anything that leaves this machine. Requires the
#                      Hardened Runtime (mandatory for notarization), a
#                      timestamp, and the entitlements in App/Elemental.entitlements.
#
# Configured by environment, never by anything checked in — a certificate name
# is not secret but it is machine-specific, and nothing here should ever hold a
# credential:
#
#   export ELEMENTAL_SIGN_ID="Developer ID Application: Your Name (TEAMID)"
#   export ELEMENTAL_NOTARY_PROFILE="elemental"     # optional, enables notarize
#
# Find the identity with:  security find-identity -v -p codesigning
SIGN_ID="${ELEMENTAL_SIGN_ID:-}"
NOTARY_PROFILE="${ELEMENTAL_NOTARY_PROFILE:-}"
ENTITLEMENTS="App/Elemental.entitlements"

sign_bundle() {
  local target="$1"
  if [[ -z "$SIGN_ID" ]]; then
    codesign --force -s - "$target"
    return
  fi
  # --options runtime is the Hardened Runtime. --timestamp is required for
  # notarization and is the one that fails when the machine is offline.
  # Deep signing is deliberately NOT used: it is documented as unreliable for
  # anything non-trivial. These bundles have a single Mach-O each, so the
  # bundle itself is the only thing to sign.
  codesign --force --options runtime --timestamp \
           --entitlements "$ENTITLEMENTS" \
           -s "$SIGN_ID" "$target"
  codesign --verify --strict --verbose=2 "$target"
}

# Submit to Apple and staple the ticket into the bundle.
#
# Stapling matters more than it looks: without it the first launch needs a
# network round trip to Apple, so a laptop opening the app offline is refused.
# With the ticket stapled the bundle carries its own proof.
#
# The profile is created ONCE, by hand, by the person with the Apple ID:
#   xcrun notarytool store-credentials "elemental" \
#       --apple-id you@example.com --team-id TEAMID --password <app-specific>
# The app-specific password comes from appleid.apple.com, never the real one.
notarize_bundle() {
  local target="$1"
  [[ -n "$SIGN_ID" && -n "$NOTARY_PROFILE" ]] || return 0
  local zip="${target}.notarize.zip"
  echo "  notarizing $(basename "$target")"
  ditto -c -k --keepParent "$target" "$zip"
  xcrun notarytool submit "$zip" --keychain-profile "$NOTARY_PROFILE" --wait
  rm -f "$zip"
  # A .saver is a plug-in bundle and staples like any other bundle.
  xcrun stapler staple "$target"
  xcrun stapler validate "$target"
}

build_render() {
  echo "==> elemental-render (offscreen still exporter)"
  swiftc "${SWIFTFLAGS[@]}" -o "$BUILD/elemental-render" \
    "${CORE[@]}" Tools/main.swift \
    -framework Metal -framework CoreGraphics -framework ImageIO \
    -framework UniformTypeIdentifiers -framework Foundation
}

build_app() {
  echo "==> Elemental.app"
  local APP="$BUILD/Elemental.app"
  mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
  cp App/Info.plist "$APP/Contents/Info.plist"
  # The three icon designs, plus the default (002) under the name Info.plist
  # declares. Baked from the Icon Composer bundles by `Elemental --make-icons`
  # and checked in, so a build needs no icon toolchain — see App/AppIcons.swift.
  cp Icons/Elemental00*.icns "$APP/Contents/Resources/"
  cp Icons/Elemental002.icns "$APP/Contents/Resources/AppIcon.icns"
  swiftc "${SWIFTFLAGS[@]}" -o "$APP/Contents/MacOS/Elemental" \
    "${CORE[@]}" App/*.swift \
    -framework AppKit -framework Metal -framework QuartzCore \
    -framework CoreLocation -framework ImageIO -framework UniformTypeIdentifiers
  sign_bundle "$APP"
  notarize_bundle "$APP"
}

build_saver() {
  echo "==> Elemental.saver"
  local SAV="$BUILD/Elemental.saver"
  mkdir -p "$SAV/Contents/MacOS" "$SAV/Contents/Resources"
  cp Saver/Info.plist "$SAV/Contents/Info.plist"
  # -Xlinker -bundle produces an MH_BUNDLE. A plain -emit-library gives an
  # MH_DYLIB, which CFBundle will not load as a plug-in — the saver then shows
  # up in System Settings and renders grey.
  swiftc "${SWIFTFLAGS[@]}" -emit-library -Xlinker -bundle \
    -o "$SAV/Contents/MacOS/Elemental" \
    "${CORE[@]}" Saver/*.swift \
    -module-name Elemental \
    -framework ScreenSaver -framework AppKit -framework Metal -framework QuartzCore
  sign_bundle "$SAV"
  notarize_bundle "$SAV"
}

embed_shader
case "$TARGET" in
  render) build_render ;;
  app)    build_app ;;
  saver)  build_saver ;;
  all)    build_render; build_app; build_saver ;;
  *) echo "unknown target: $TARGET" >&2; exit 1 ;;
esac
echo "done -> $BUILD"
