#!/bin/bash
#  Elemental — CLI build. No Xcode project, no Metal toolchain.
#
#  Scene.metal is embedded into the binary as a Swift string and compiled by the
#  Metal runtime at launch. That is what makes the screensaver work: it does no
#  file I/O at all, so the legacyScreenSaver sandbox has nothing to deny.
#
#  Usage:  ./build.sh [render|app|saver|all]      (default: all)

set -euo pipefail
cd "$(dirname "$0")"

export DEVELOPER_DIR=/Library/Developer/CommandLineTools
TARGET="${1:-all}"
BUILD="build"
mkdir -p "$BUILD"

# ---------------------------------------------------------------- shader embed
# Regenerate Core/ShaderSource.swift from Core/Scene.metal. Edit the .metal
# file; never edit the generated .swift.
embed_shader() {
  local src="Core/Scene.metal" out="Core/ShaderSource.swift"
  if [[ -f "$out" && "$out" -nt "$src" ]]; then return; fi
  echo "  embedding $src"
  {
    echo "//  ShaderSource.swift — GENERATED by build.sh from Core/Scene.metal."
    echo "//  Do not edit. Edit Scene.metal and rebuild."
    echo ""
    echo "enum ShaderSource {"
    echo "    static let metal = #\"\"\""
    cat "$src"
    echo "\"\"\"#"
    echo "}"
  } > "$out"
}

# Config lives in Core because the saver needs it too — it tries to read the
# app's settings and falls back to defaults when the sandbox says no.
CORE=(Core/SceneState.swift Core/Astro.swift Core/Simulation.swift \
      Core/Renderer.swift Core/Config.swift Core/Weather.swift \
      Core/Furniture.swift Core/Observation.swift Core/Calibration.swift Core/ShaderSource.swift)

SWIFTFLAGS=(-O -wmo)

# ---------------------------------------------------------------- targets

build_render() {
  echo "==> elemental-render (offscreen still exporter)"
  swiftc "${SWIFTFLAGS[@]}" -o "$BUILD/elemental-render" \
    "${CORE[@]}" Tools/main.swift \
    -framework Metal -framework CoreGraphics -framework ImageIO \
    -framework UniformTypeIdentifiers -framework Foundation
}

build_app() {
  echo "==> Elemental.app"
  local APP="$BUILD/Elemental.app"
  mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
  cp App/Info.plist "$APP/Contents/Info.plist"
  # The three icon designs, plus the default (002) under the name Info.plist
  # declares. Baked from the Icon Composer bundles by `Elemental --make-icons`
  # and checked in, so a build needs no icon toolchain — see App/AppIcons.swift.
  cp Icons/Elemental00*.icns "$APP/Contents/Resources/"
  cp Icons/Elemental002.icns "$APP/Contents/Resources/AppIcon.icns"
  swiftc "${SWIFTFLAGS[@]}" -o "$APP/Contents/MacOS/Elemental" \
    "${CORE[@]}" App/*.swift \
    -framework AppKit -framework Metal -framework QuartzCore \
    -framework CoreLocation -framework ImageIO -framework UniformTypeIdentifiers
  codesign --force -s - "$APP"
}

build_saver() {
  echo "==> Elemental.saver"
  local SAV="$BUILD/Elemental.saver"
  mkdir -p "$SAV/Contents/MacOS" "$SAV/Contents/Resources"
  cp Saver/Info.plist "$SAV/Contents/Info.plist"
  # -Xlinker -bundle produces an MH_BUNDLE. A plain -emit-library gives an
  # MH_DYLIB, which CFBundle will not load as a plug-in — the saver then shows
  # up in System Settings and renders grey.
  swiftc "${SWIFTFLAGS[@]}" -emit-library -Xlinker -bundle \
    -o "$SAV/Contents/MacOS/Elemental" \
    "${CORE[@]}" Saver/*.swift \
    -module-name Elemental \
    -framework ScreenSaver -framework AppKit -framework Metal -framework QuartzCore
  codesign --force -s - "$SAV"
}

embed_shader
case "$TARGET" in
  render) build_render ;;
  app)    build_app ;;
  saver)  build_saver ;;
  all)    build_render; build_app; build_saver ;;
  *) echo "unknown target: $TARGET" >&2; exit 1 ;;
esac
echo "done -> $BUILD"
